### ISSUE TITLE
Faster downloads

### ISSUE THREAD

**Issue by brliron** [thpatch/thcrap#106]
I've got complaints from Plasma that the initial thcrap_configure loading (the repos download just before displaying the patch list) is too slow. And I've got complaints from myself that the thcrap_loader file check is too slow. We need to do something for both problems.

Some suggestions for thcrap_configure:
- Do not use the fastest server, just use a random one.
It actually takes time to choose the fastest server, you have to ask every server about its speed.
- Remove nmlgc servers from the list. I think it's still there somewhere.
- Ask several servers at the same time, don't wait for a server to answer before asking to the next one.

We may not do the 1st one if we do the 3rd one and it yields good results. We may also delay the 1st one until we actually need to download a patch from a server.

I also remember some discussion a few years ago about HTTP2. The only upside I remember was being able to download several files simultaneously. Which is good, we could download all the mirrors.thpatch.net/*/repo.js in one go. Which makes me think, about the 1st suggestion, do we check the mirrors.thpatch.net ping for every repo? We sure don't need to.
As for the downsides of HTTP2, I think there was something about wininet not supporting it, which would require us to switch to cURL. And maybe something about XP?

And I remember reading about several apps slowed by something called......... I can't remember that name. But the point was, by default, the TCP recipient won't answer immediately after receiving a packet, it will wait because it might get 2 or 3 more packets, ack them all at once, and by doing this it saves bandwidth. This is definitely something we want when we download a 4 MB font, but it might slow down things when downloading tiny text files. We may want to look at this and do some benchmarks.

The http2 one and the one about the TCP icantrememberthename can also be useful for thcrap_loader.

**Comment by brliron** [comment]
While we do a netcode recoding, we could add proxy support at the same time.

**Comment by Mokou** [comment]
Is the TCP thing you're thinking of [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm)? If so we already deal with it, and I'm pretty sure Cloudflare does too.

As for optimizing downloads @james7132 and I were talking about this just recently. I think the idea was to use https://github.com/HouraiTeahouse/Tapioca. It's a bit more involved than just speeding up repo.js downloads, but I think it would help with this as well.

In the shorter term convincing third party modders to place the `https://mirrors.thpatch.net/REPO_NAME` link above the other links and getting rid of nmlgc links would help. Something else we could do to eek out even more speed might be to consolidate all the third party repos into one so we don't have to download 20 different `repo.js` files. That would be slightly more involved though.

**Comment by brliron** [comment]
We will create a new branch, and:
1. build libcurl with thcrap ;
2. port the current netcode to libcurl ;
3. rewrite our netcode to support parallel downloads.
1. and 2. should be quite easy, and 3. can be done step by step. I'll start with 1. and 2.

**Comment by H4M5TER** [comment]
Is this done? Initialization is still slow.
Without modifying net module, buffering might be good for faster initialization.
And I'm looking forward to proxy support.

**Comment by brliron** [comment]
It's done, we did everything we could think about to enhance download speed. But I'm not an expert in networks, so I may have missed something. What do you mean by buffering? This word means so many things in the computers' world.

Someone talked to me this morning about slow download speeds in China, and told me they are considering setting up their own thcrap server in China. If this happens, this may help a lot with download speed for you.

As for proxies, well, I completely forgot about them.
We use libcurl for our internet connections, and according to the documentation (https://curl.se/libcurl/c/CURLOPT_PROXY.html), users can set the environment variables http_proxy and https_proxy to set a proxy themselves (there are many pages on the web explaining how to set an environment variable, here is one: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html). It would be better if thcrap could detect it automatically, but I don't think we'll find enough time to work on it in the near future, so in the meantime, that's better than nothing.

**Comment by H4M5TER** [comment]
For buffering, I mean just save the list of repoes to not to download it every time.

**Comment by H4M5TER** [comment]
Thank you for the proxy solution.
I don't want to set the env permanently.
So I tried this in commandline and it works.
```
set HTTP_PROXY=http://localhost:7890
set HTTPS_PROXY=%HTTP_PROXY%
thcrap_configure_v3.exe
```
