### ISSUE TITLE
Weird up-key pushing when game started with thcrap in th165+ games

### ISSUE THREAD

**Issue by Yanstory** [thpatch/thcrap#117]
When starting game with thcrap, after splash screen, the up key will be pushing and game will continually react with it. That means you cannot play the game well, because cursor will always jump between menu items and player will always go to top of the screen.

**Comment by 32th-System** [comment]
Attach your thcrap_log.txt. If it happens in th06 and th07 and you ever leave the window unfocused while you are starting the game, that's a ZUN bug

**Comment by Yanstory** [comment]
I launched th165 & th17 with either ``zh-hans`` or ``en`` language pack but it also happens. All keys work well except up key is kept pushing.
I'll attach ``thcrap_log`` later after ``en`` patch finished updating.

**Comment by AsyrafFile** [comment]
That remind me of certain thcrap-tsa issue not yet patched out by nmlgc.
https://github.com/thpatch/thcrap-tsa/issues/25#issue-369893947

**Comment by ManDude** [comment]
That glitch will make the down key have priority, NOT the up key like described.

**Comment by Yanstory** [comment]
idk but it shows as up key on my computer, because in the game the player and menu cursor always goes to (screen) top when no key is hold.

**Comment by Yanstory** [comment]
I found why this happed. I installed a visual joystick program and it always be actived, so the game keep react with v-joys. I've uninstalled and all things gone.
