### ISSUE TITLE
thpatch/lang_en/ causes crashes on PCB

### ISSUE THREAD

**Issue by NaokiP** [thpatch/thcrap#118]
Hi,

Latest version of thpatch/lang_en/ seems to be causing 100% crashes in PCB when boss' name and title is supposed to appear. Unpatched game does not have this issue, and patched exe without lang_en on the config modlist runs fine too. Tested on Letty, Chen, Alice.

Log file reports this near the end on crash for Chen:
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/3618538/thcrap_log.txt)
Exception c0000005 at 0x6243F6EF (Rxf6ef) (\MSVCR120.dll)

Registers:
EAX: 0x00000002 ECX: 0x0000003A EDX: 0x00000002 EBX: 0x00000001
ESP: 0x0019FC50 EBP: 0x0019FC7C ESI: 0x0E589100 EDI: 0x0918F20A

Stack trace:
[06] 0x7750BBA6 (Rx6bba6) (\ntdll.dll)
[05] 0x7750808B (Rx6808b) (\ntdll.dll)
[04] 0x77514216 (Rx74216) (\ntdll.dll)
[03] 0x5DE84137 (Rx24137) (\thcrap_tsa.dll)
[02] 0x5DE8305C (Rx2305c) (\thcrap_tsa.dll)
[01] 0x6240AEE8 (Rxaee8) (\thcrap.dll)

And this, very similar, for Alice (Stack trace is same):
[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/3618539/thcrap_log.1.txt)

Exception c0000005 at 0x567CF6EF (Rxf6ef) (\MSVCR120.dll)

Registers:
EAX: 0x00000002 ECX: 0x0000003A EDX: 0x00000002 EBX: 0x00000001
ESP: 0x0019FC50 EBP: 0x0019FC7C ESI: 0x0C217100 EDI: 0x08BDCB2A

I tried updating my Visual C++ 2013 after seeing msvcr120 and some googling, but it doesn't seem to have done anything

Windows 10, Japanese Locale/Region

I can provide further files or details and run further tests if necessary, thank you

**Comment by brliron** [comment]
Hi. Does it crash if you have both thpatch/lang_en and thpatch/skipgame?

**Comment by NaokiP** [comment]
Yep, still crashes even with skipgame. Removing lang_en once again removes the crashing issue. Here's a log from Stage 1. 
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/3660815/thcrap_log.txt)

I've also tried with and without vpatch, same result.
Out of curiosity, I tried lang_de as well, same problem even if I remove lang_en from the stack.
[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/3660826/thcrap_log.1.txt)

I'm not sure how any of this works, but could having two different lang patches crash the same way point to a problem with base_tsa somehow?

**Comment by DoremyR3d** [comment]
It's hard to reproduce, since it changes with every version of thcrap
Graphical artifacts and crashes are caused by the d3d8.dll file that can be found in the root folder of certain version of the game. Removing the dll fixes the problem.
