### ISSUE TITLE
Allocate executable memory for binhacks

### ISSUE THREAD

**Issue by brliron** [thpatch/thcrap#122]
Some modders want to make big binhacks, that don't fit in a few bytes. If would be useful if we could allocate some memory for them.

Proposal syntax:

```js
binhack: {
  "my_binhack" : {
    code: "e9[codecave:my_codecave]",
    addr: "Rx01234567"
  }
},
codecave: {
  my_codecave: "90909090e9[Rx0123456c]"
}
```
That doesn't sound hard to do. Codecave: just alloc some executable memory and feed it to the binhack parser.
Reference in binhacks: keep a list of all codecaves, strcnmp on "codecave:" around or in the func_get call.

**Comment by ManDude** [comment]
Could also solve potential codecave clashing issues.

**Comment by 32th-System** [comment]
https://github.com/thpatch/thcrap/pull/123
One thing I may change is to change the syntax to not require `"code": "..."` as that seems redundant

**Comment by brliron** [comment]
Ok, so... The syntax in c82910ec69c7b87d316f7cb19c2685f31f984160 was
```js
codecave: {
  my_codecave: {
    "code": "90909090e9[Rx0123456c]"
  }
}
```
and the syntax in b0f392b73571701fb07dcbaacdbe62643c503ccb is now
```js
codecave: {
  my_codecave: "90909090e9[Rx0123456c]"
}
```
Am I right?

**Comment by 32th-System** [comment]
Yes

**Comment by brliron** [comment]
Ok

If you don't mind, I'll wait until the restructuring fix release before merging.

**Comment by 32th-System** [comment]
Alright
