### ISSUE TITLE
end00b.end.jdiff crashes the game (th06)

### ISSUE THREAD

**Issue by Azzara** [thpatch/thcrap#127]
Just trying out the new feature for translating ending in th06.
end00b.end.jdiff crashes the game. Always. Doesn't matter if end00b.end exists or not.
The other endings don't crash. I used skipgame for testing.

Also, Remilia's lines from *.end.jdiff are ignored and they appear in Japanese. Unless the corresponding *.end file exist in which case only Remilia's lines are used from the end.jdiff but everything else in the end.jdiff is ignored.

By the way, how do I delete the binary endings like end00b.end from the thpatch-server?

**Comment by 32th-System** [comment]
Send me a thcrap_log.txt as well as your end00b.end.jdifff. As for why some lines don't get translated, the thing that detects if this is a line to display in the game or a command in the ending file is quite wrong

**Comment by brliron** [comment]
And to delete a binary ending, delete the corresponding wiki page.
For example, for lang_en/th06/end00.end, you go to the file on the thpatch wiki (https://www.thpatch.net/wiki/File:lang_en-th06-end00.end), you hover the arrow in the top right corner (just on the right of read/edit/show history), and you click on "Delete".

**Comment by Azzara** [comment]
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/4449332/thcrap_log.txt)
[end00b.end.jdiff.txt](https://github.com/thpatch/thcrap/files/4449351/end00b.end.jdiff.txt)
I had to rename the jdiff file to jdiff.txt before uploading.

Oh, now I also get a vpatch error message box when I start the game. Did something change in the last 12 hours? Anyway, I didn't get this message before so it is probably unrelated.

I can reproduce the problem with both the Bulgarian and Brazilian translations. I haven't tried the other ones.
The other bad ending works although it looks almost the same. So it might not be a translation issue.

**Comment by 32th-System** [comment]
Fixed by https://github.com/thpatch/thcrap/commit/a9a707cb3d1ea9b576cdb7c0a28db2525d61daa3
