### ISSUE TITLE
Latest thcrap release crashes after selecting patches under WINE.

### ISSUE THREAD

**Issue by Kho-Dialga** [thpatch/thcrap#130]
When I try to patch a Touhou game with thcrap, it breaks after I select the patches that I want to apply and it crashes. This doesnt happen with older releases. This also happens under clean winepreixes
Here's the backtrace.txt file,
[backtrace.txt](https://github.com/thpatch/thcrap/files/5406014/backtrace.txt)
and here's a screenshot of thcrap before it crashed.
![pic-selected-201019-2058-07](https://user-images.githubusercontent.com/55767703/96535119-623f5980-124e-11eb-9bf9-adb0e06c6d25.png)

I'm running Gentoo Linux and WINE staging 5.19

**Comment by 32th-System** [comment]
Could you send the files in your `logs/` folder? They contain the exact version number of your thcrap installation. I don't think you actually have the latest thcrap version based on the backtrace.txt

My (very technical) reason for that is that it says that there's a "RepoDiscoverAtURL" function in the backtrace when the latest version doesn't have this function anymore

**Comment by Kho-Dialga** [comment]
[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/5436181/thcrap_log.1.txt)
[thcrap_log.2.txt](https://github.com/thpatch/thcrap/files/5436182/thcrap_log.2.txt)
[thcrap_log.3.txt](https://github.com/thpatch/thcrap/files/5436183/thcrap_log.3.txt)
[thcrap_log.4.txt](https://github.com/thpatch/thcrap/files/5436184/thcrap_log.4.txt)
[thcrap_log.5.txt](https://github.com/thpatch/thcrap/files/5436185/thcrap_log.5.txt)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/5436186/thcrap_log.txt)

Here are the log files, I'll try the newest release later today.

**Comment by Kho-Dialga** [comment]
I just tried the latest thcrap release and it worked perfectly. I just need to copy bin/thcrap_update.dll to the thcrap folder. Should I close this issue now?
