### ISSUE TITLE
Old Patcher Does Not List All Current Patches, and New Patcher Does Not Run At All in Windows XP

### ISSUE THREAD

**Issue by RobertMVelasquez1996** [thpatch/thcrap#134]
The patcher does not list all patches it views with a JSON error on many servers when run in Windows XP for an older version and it does not run at all when trying the latest version with a KERNEL32 error when ran. So, is the patcher only going to work now on Vista and later? I am asking because I would like to play the games in English in Windows XP, but I cannot at all. I can play the patched games on Windows 7 for all games (mainly shooting games, but have tried VD also).

**Comment by brliron** [comment]
This should be fixed with the new version (2021-01-17)
