### ISSUE TITLE
Missing Changes 

### ISSUE THREAD

**Issue by Yuyutato** [thpatch/thcrap#135]
This is my First Time Experimenting with thcrap and I've noticed that some Changes aren't showing up. I'm Edditing the Dialouge and Basing that off the Official English Translations so I Coppied them across and only some Changes including those are Appearing.

For Example I Can Change the Kanji on the SA Title Screen but the Sprites Won't Change. These sprite Changes do affect the game the though if I Compile a .dat and Replace it.

Is there somthing I'm Doing Wrong?

Sorry if this is the Wrong Place to Post this Problem as it might just be Human error and not a bug

**Comment by brliron** [comment]
ZUN games patching usually works well, so I would guess on human error (no offense). We usually help with debugging them on Discord, but here is fine too.

Here are some debugging tips:
- In your thcrap directory, you have a "logs" directory, with a few log files. thcrap_log.txt is the most recent log file and the thcrap_log.X.txt files are older log files.
- Around the top of the log file, look for this section:
```
---------------------------
Patch stack:
---------------------------
```
You want to make sure your patch is listed here, with the correct path.
- Look for the "Resolving" log lines. Here is an example where thcrap didn't change a file:
```
(Data) Resolving megamari/data/enemy/bullet0000/0012.bmp... not found
(JSON) Resolving megamari/data/enemy/bullet0000/0012.bmp.jdiff... not found
```
And an example where thcrap replaced a file:
```
(PNG) Resolving megamari/data/enemy/bullet0000/0012.png...
    + D:/thcrap/thcrap_build_wsl/thcrap_test/repos/thpatch/lang_en/megamari/data/enemy/bullet0000/0012.png
```
Another example with the th16 title logo:
```
(PNG) Resolving th16/title/title_logo.png... 
    + D:/thcrap/thcrap_build_wsl/thcrap_test/repos/thpatch/lang_en/th16/title/title_logo.png
     + D:/thcrap/thcrap_build_wsl/thcrap_test/repos/thpatch/lang_fr/th16/title/title_logo.png
```
Here, thcrap will use the last file, which is the one from lang_fr.

**Comment by 32th-System** [comment]
I was able to confirm that this issue got resolved
