### ISSUE TITLE
Patch stacking shortcut

### ISSUE THREAD

**Issue by MagicalDrizzle** [thpatch/thcrap#137]
Say you have a bunch of patches installed, and you want to try combinations of them (en-loddk/en-rng/en-loddk-rng-alphes etc). Currently you have to manually create and edit a new config file for every indiviual combination you desire. I suggest having a seperate shortcut maker that detect the patches you have downloaded and offer an option to stack patches however you like, and then automatically create a shortcut pointing to the desired config.
I hope I managed to convey what I meant.

**Comment by brliron** [comment]
Hi. We already have plans about making a new UI - actually, that's something we've been discussing for a few years. But we still don't even know what kind of UI we want. Do we want a wizard, a launcher that works with a new thcrap_configure, a launcher that replaces thcrap_configure, something else? And even if we knew, I don't think any of us would have time to work on it right now.
But we want to make a new one, we don't like the current one, and hopefully it will happen one day.
