### ISSUE TITLE
Problem with Touhou 18: Unconnected Marketeers patch

### ISSUE THREAD

**Issue by Marisa-the-creeper** [thpatch/thcrap#138]
I downloaded the demo for Touhou 18: Unconnected Marketeers from moriyashrine.org and i applied the french patch for the game, but when I tried to launch it, I recieved multiple error messages about the .js files of the patch. I tried to launch the game by itself and it worked perfectly. I tried to use the english patch but the result was the same. After reinitialising the patch and going through all the error messages, the game launched but nothing was translated. The game was released litteraly two days ago, so maybe it's normal but if you didn't know about that problem, then now you do!

Take your time, coding isn't an easy task

**Comment by Marisa-the-creeper** [comment]
![error message 1](https://user-images.githubusercontent.com/81262093/112211820-8bf51600-8c1c-11eb-8233-21534e6680ed.jpg)
![error message 2](https://user-images.githubusercontent.com/81262093/112211825-8c8dac80-8c1c-11eb-8698-7ab2f7a9a5b6.jpg)

they show up just after opening the shortcut and after clicking "run game"

**Comment by 32th-System** [comment]
Try again now, it should be fixed

**Comment by DankRank** [comment]
Alright, it should be fixed for real now. But also, this problem only happens on older versions of thcrap, so you should probably update.

**Comment by Marisa-the-creeper** [comment]
I had to reinstall the patch because the update doesn't work(im used to it,
i just download the newest version every now and then) and it's all good
now! Thanks!
