### ISSUE TITLE
THCRAP/THTK causes memory leak

### ISSUE THREAD

**Issue by Oreeeee** [thpatch/thcrap#140]
After a few minutes, RAM usage rises from 2.1 GB to 4 GB

**Comment by brliron** [comment]
- Is this thcrap or thtk? They have almost nothing in common, a memory leak in one will probably not be in the other.
- How are you running it?
  - For thcrap, we need at least the game and patch stack. The full log file could help.
  - For thtk, we need to know which tool, and which parameters you used.

**Comment by Oreeeee** [comment]
@brliron 
-Both of them
-For THCRAP game was Touhou 15
-For THTK I was trying to unpack Touhou 8 files using THDAT

And how can I get log?

**Comment by DankRank** [comment]
It's in `logs/thcrap_log.txt` in the directory where you have thcrap

**Comment by Oreeeee** [comment]
@DankRank Thanks, I will do this after lessons

**Comment by brliron** [comment]
For thtk, if it works correctly, you shouldn't be able to see a memory leak after a few minutes, because the tool doesn't run for a few minutes. I just tried it on my end, with the following command:
```
thdat -x 8 th08.dat
```
using the last thtk version from https://github.com/thpatch/thtk/releases/tag/12 and a th08.dat with a sha256 of 9D7EDF43B8DDD347CBB641836F6B5050745DD936F688DAEBBF9382CA557043BB, the tool does its job in about 3 seconds and exits.

**Comment by Oreeeee** [comment]
@DankRank Sorry that I am being very late. Here are my logs. After removing all things about Touhou/THCRAP/THTK I no longer have memory leak or any other RAM related issue.
[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/6448486/thcrap_log.1.txt)
[thcrap_log.2.txt](https://github.com/thpatch/thcrap/files/6448487/thcrap_log.2.txt)
[thcrap_log.3.txt](https://github.com/thpatch/thcrap/files/6448488/thcrap_log.3.txt)
[thcrap_log.4.txt](https://github.com/thpatch/thcrap/files/6448489/thcrap_log.4.txt)
[thcrap_log.5.txt](https://github.com/thpatch/thcrap/files/6448490/thcrap_log.5.txt)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/6448491/thcrap_log.txt)

**Comment by Oreeeee** [comment]
Fuck you

**Comment by brliron** [comment]
You're welcome :)
