### ISSUE TITLE
Directory not found using WINE on Linux

### ISSUE THREAD

**Issue by porky11** [thpatch/thcrap#141]
I tried to run this on my Linux system (Manjaro) and `thcrap_configure.exe` works as expected until I have to select the directory, where I put my games.
Then I get these lines:

```
(JSON) Resolving versions.js... not found
ERROR: No version definition file (versions.js) found!
Seems as if base_tsa didn't download correctly.
Try deleting the thpatch directory and running this program again.
No game locations found.
Search in a different directory?
```

I tried to delete `repos/thpatch`, but then the program just quits after two messages.

**Comment by brliron** [comment]
This is a known bug with Wine. Copy all the DLL files from the thcrap/bin directory to the thcrap directory and try again, it should work.

**Comment by Sparen** [comment]
If the solution to this is known, it should be placed onto the instructions on the Wiki

**Comment by brliron** [comment]
No offense, but I copied my previous answer from https://www.thpatch.net/wiki/Touhou_Patch_Center:Download#There_is_an_error_about_.22version.js_not_found.22_when_using_Wine_.28Linux_and_Mac.29 . Maybe you can think of a better place to put it?

**Comment by Sparen** [comment]
I didn't realize it was actually located there - the language `Windows XP with at least Service Pack 2, or a later version of Windows; also works with Wine` implied to me that thcrap should work out of the box for its intended use case on Wine without any manual modifications required. A link in the System Requirements or Detailed instructions to that part of the page would reduce confusion.

**Comment by brliron** [comment]
Good point.

**Comment by brliron** [comment]
I just fixed this bug, the fix will be included in the next version.
