### ISSUE TITLE
Latest thcrap crash the games on linux.

### ISSUE THREAD

**Issue by hmtheboy154** [thpatch/thcrap#143]
When running on Linux using wine, the newest update of thcrap require not only copy `thcrap_update.dll` out from `bin`, but also `libcurl.dll`, `libssl-1_1.dll` and `libcrypto-1_1.dll`. I did all of that and then got into the loader. But then this happen

![image](https://user-images.githubusercontent.com/39849246/120115304-584ee300-c1ad-11eb-9625-1bc024f793d6.png)

Is there anything I can provide in order to fix this ?

**Comment by 32th-System** [comment]
Could you send your thcrap_log.txt?

**Comment by hmtheboy154** [comment]
Here is mine
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/6567180/thcrap_log.txt)

**Comment by 32th-System** [comment]
This log seems to be just for the loader. There should be more logs in the logs folder

**Comment by hmtheboy154** [comment]
But 6 files in the `logs` folder are the same. Do you want me to run configure or something ?

**Comment by Sonickyle27** [comment]
I am also getting this issue on Arch Linux, running through Lutris with Wine 6.9. Here are my two logs from the logs folder. This stops the configure tool from working after pressing Enter, and games launched using shortcuts cannot run too.

[thcrap_log.txt](https://github.com/thpatch/thcrap/files/6571012/thcrap_log.txt)
[utl-log.txt](https://github.com/thpatch/thcrap/files/6571013/utl-log.txt)

**Comment by 32th-System** [comment]
> I am also getting this issue on Arch Linux, running through Lutris with Wine 6.9. Here are my two logs from the logs folder. This stops the configure tool from working after pressing Enter, and games launched using shortcuts cannot run too.
> 
> [thcrap_log.txt](https://github.com/thpatch/thcrap/files/6571012/thcrap_log.txt)
> [utl-log.txt](https://github.com/thpatch/thcrap/files/6571013/utl-log.txt)

This might an unrelated issue. This is because you are getting a crash log, but OP isn't. Redownloading thcrap should fix it

Technical explanation:
- thcrap.dll is updated but thcrap_update.dll isn't.
- thcrap_update.dll is trying to do something that in the new version is unsupported
- That being calling PROJECT_NAME_SHORT as a function, when in the new version it's not code, but data

**Comment by infiWang** [comment]
Overwrite dlls in `thcrap` directory by dlls in 'thcrap/bin' after first prompted auto update fix the issue for me.

**Comment by brliron** [comment]
Oh. Yeah, that definitely explains it. After an update, the DLLs in the bin directory are updated, but the ones in the root directory aren't.

**Comment by hmtheboy154** [comment]
Today I tried to pull latest thcrap and then reinstall the whole wine packages (32 & 64) the games can run now
Thanks for noticing this post, I'm gonna close the issue now.
