### ISSUE TITLE
EoSD crashes when the ending is reached (Easy difficulty)

### ISSUE THREAD

**Issue by ack7139** [thpatch/thcrap#144]
As the title suggests, doing a normal run of EoSD in easy difficulty will cause the game to crash when the ending is reached. This has a 100% chance of happening (in my case at least).
OS is Windows 10 20H2, "VsyncPatch" and "DX8 to DX9 converter" were applied. I've only used Reimu A when I was testing.
This bug was first mentioned here: https://github.com/ack7139/thprac/issues/32. A Windows minidump file was attached there and may come to be helpful.

Log file: [thcrap_log.txt](https://github.com/thpatch/thcrap/files/6643750/thcrap_log.txt)

**Comment by ManDude** [comment]
Thanks for the report! We're working on this right now so don't worry.

**Comment by brliron** [comment]
Fixed in thpatch/thcrap-tsa@c459649d1a081a9e959cada4bcae2ecd95ec8028
