### ISSUE TITLE
Touhou 9.5 Shoot the Bullet Steam release isn't recognized

### ISSUE THREAD

**Issue by Alpha272** [thpatch/thcrap#145]
thcrap doesn't find the th095 steam release.

![image](https://user-images.githubusercontent.com/22331613/122649764-c729b700-d12f-11eb-93f4-afa741b401ce.png)

When I add it by hand (ie. write it into games.js), it doesn't patch the game

![image](https://user-images.githubusercontent.com/22331613/122649834-2c7da800-d130-11eb-99c9-69aa9daf445d.png)

**Comment by brliron** [comment]
This is being worked on, please wait warmly~

**Comment by DankRank** [comment]
done

**Comment by Alpha272** [comment]
I.. wow.. that was fast
