### ISSUE TITLE
Steam version of touhou 17.5 isn't recognised ? 

### ISSUE THREAD

**Issue by Naia-love** [thpatch/thcrap#159]
The demo (~~dl from Moriya~~) is recognised: 
![image](https://user-images.githubusercontent.com/26840567/141983646-764d0b90-8e2a-4e4f-8375-c63169fc18b5.png)

But not the full game on steam : 
![image](https://user-images.githubusercontent.com/26840567/141983797-a3539245-cb50-4382-ba19-369de0ab8072.png)
![image](https://user-images.githubusercontent.com/26840567/141983815-3fce28c7-e5ba-47d6-8d8c-ce4ddd0dd7c6.png)

same with the other version of the tool

I'm on Void Linux, using proton 6.3-7 for both thcrap and the game (game that I have played a bit and work fine).

**Comment by 32th-System** [comment]
thcrap support for the full game is still being worked on

**Comment by brliron** [comment]
Fixed
