### ISSUE TITLE
th175 - non-japanese characters support

### ISSUE THREAD

**Issue by brliron** [thpatch/thcrap#165]
We need to look at non-japanese characters for story mode. It might just be a matter of changing the font to Touhou Biolinum.

**Comment by 32th-System** [comment]
Fonts can be changed very easily by simply providing a replacement for any of the font files in the game's archive files. The main dialoge font is `data/font/KH-Dot-Dougenzaka-16.ttf`

**Comment by brliron** [comment]
Done in thpatch/thcrap-tsa@f6cba91101580d29153904081aa799287aaaed58

**Comment by ROCO-freedom** [comment]
Perhaps the key is to support the `Codepage` modification of the text, as long as the font file contains the characters required for language localization, it can be used normally.
