### ISSUE TITLE
Touhou 18 will crash in Wine if cjkfonts is installed with winetricks

### ISSUE THREAD

**Issue by 32th-System** [thpatch/thcrap#174]
Wine versions tried: Wine 6.23, Proton 6.3
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/7740954/thcrap_log.txt)
[backtrace.txt](https://github.com/thpatch/thcrap/files/7740956/backtrace.txt)

**Comment by hmtheboy154** [comment]
so that's why..... I confirm having the same problem

**Comment by 32th-System** [comment]
@hmtheboy154 [Is it fixed for you now?](https://github.com/thpatch/thcrap-tsa/commit/70f377dd23857061374482dacc5d4b536c010b74)

**Comment by hmtheboy154** [comment]
still crashing

**Comment by hmtheboy154** [comment]
wait no, the game run after some retry, I don't know why (the new .js is already there). But it is working now

Tested with a wineprefix with a lot of dlls installed using winetricks and a prefix with only cjkfonts

**Comment by hmtheboy154** [comment]
Tested with lutris-Ge-7.24, Wine 7.14 & Wine 7.0

This screenshot is from lutris-GE, with a new prefix that only install cjkfonts
![Screenshot_20220812_235425](https://user-images.githubusercontent.com/39849246/184406824-3df4eb94-028b-4901-b9f3-6f5061c5f889.png)

**Comment by 32th-System** [comment]
I also tested it myself in a VM and can confirm that it works
