### ISSUE TITLE
Patched games crash during dialogs in Wine

### ISSUE THREAD

**Issue by thvanyk** [thpatch/thcrap#198]
wine version: 3.0.5 (also tried 4.7-staging);
.dotnet version: 4.7 (the same problem if there is dotnet 2, wine mono or no dotnet);
DirectX is installed (also tried without DirectX).

Touhou 11, 14, 15, 18.5 work perfectly without patches.
But if there are any patches Touhou 11 and 14 crash when a dialog begins. The problem probably occurs if the game is launched with base_tsa patch.
![Screenshot_20220918_084225](https://user-images.githubusercontent.com/113838671/190913528-f5e425f0-dddb-4a48-88b1-898a8377b287.jpg)

Logs:
[backtrace.txt](https://github.com/thpatch/thcrap/files/9594235/backtrace.txt)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/9594258/thcrap_log.txt)

This problem was not detected in Touhou 15 and 18.5.

**Comment by thvanyk** [comment]
I tried to find the cause of this bug. It is caused by sprintf_call binhacks. After commenting the lines with these binhacks Touhou 11 and 14 stopped crashing during dialogs and seems that dialogs are shown without bugs. But after that the game started crashing during spellcards. The crash was caused by spell_align and result_spell_align, so I commented them. After that the game stopped crashing during spellcards, but the spell name position align is incorrect. After thar I managed to clear all stages without crashes. Also some patches were tested and they worked perfectly.

Touhou 11:
![Screenshot_20220922_174540](https://user-images.githubusercontent.com/113838671/191782039-c9ccae20-3d50-4ce2-a61d-29d8c9f43467.jpg)

Touhou 14:
Before:
![Screenshot_20220920_152138](https://user-images.githubusercontent.com/113838671/191783097-4a41285e-de52-416c-905a-a65b7f309504.jpg)
![Screenshot_20220920_160349](https://user-images.githubusercontent.com/113838671/191783173-312f885d-a126-4429-9108-5b5bfd0f1793.jpg)
After:
![Screenshot_20220922_081336](https://user-images.githubusercontent.com/113838671/191783421-3dfe6e8c-cefa-4105-af02-6584f13ff892.jpg)
![Screenshot_20220922_081422](https://user-images.githubusercontent.com/113838671/191783464-86fb3142-0d2e-4bf8-adc1-199c83d97b2b.jpg)

DDC with some patches:
![IMG_20220922_181012](https://user-images.githubusercontent.com/113838671/191785201-a74dcdfa-b971-486b-9d37-dd9b17dc1032.jpg)

I do not close the issue because this is just removing some binhacks from base-tsa patch and other patches with binhacks can cause the same problem.

Archive with modified files (commented binhacks, which cause crashes) in case you have the same problem (put them into nmlgs/base_tsa):
[base_tsa.zip](https://github.com/thpatch/thcrap/files/9627192/base_tsa.zip)

**Comment by 32th-System** [comment]
Does it still happen? If so, could you try replacing your thcrap.dll with the one in this zip file?
[thcrap.zip](https://github.com/thpatch/thcrap/files/10549363/thcrap.zip)

**Comment by zero318** [comment]
What hardware/software configuration was used when encountering this? The provided logs have blanks where that information would normally be.

**Comment by thvanyk** [comment]
I deleted all patches, replaced thcrap.dll with the one in the zip file, and downloaded English language patch again (which depends on base_tsa), but DDC crushes again on dialogs (which can be fixed by commenting the binhacks).
![Screenshot_20230205_073636](https://user-images.githubusercontent.com/113838671/216807749-ece6e60f-ed98-4b5d-a235-93c8c982281b.jpg)

CPU is MediaTek Helio P60 (ARMv8-A), but i386 can be emulated using Exagear. Environment configurations:
`mesa_glthread=true WINEDEBUG=-all MESA_NO_ERROR=1 MESA_DEBUG=silent VTEST_SOCK= VTEST_WIN=1 ZINK_DESCRIPTORS=lazy`
WineD3D versions which were used: 2.6, 3.17, 6.17.
Overrided libraries:
![Screenshot_20230205_111804](https://user-images.githubusercontent.com/113838671/216808783-56a57b3f-ca8c-4d99-96d2-96eda46d5284.jpg)

**Comment by zero318** [comment]
It seems like this is an issue with improper emulation of a specific unusual x86 instruction encoding. Fortunately it _should_ be easily fixable on our end by switching to a standard encoding instead, so I'll start tracking down and fixing all of those. This should be reported to the Exagear devs as well if at all possible.

Specifically there are 4 redundant ways of encoding an offset from ESP using the SIB byte (0x24, 0x64, 0xA4, and 0xE4), but only the 0x24 encoding is generated by compilers and assemblers. Thcrap was using the 0xE4 encoding for some reason, which appears to be decoded as ESP plus some other value *8, thus crashing.

**Comment by thvanyk** [comment]
Yes, it seems like it is an emulation problem. After the update it works without crashes. Thank you.

**Comment by DankRank** [comment]
@zero318 turns out the 0xE4 encoding is generated by ollydbg
