### ISSUE TITLE
Support advanced image patching

### ISSUE THREAD

**Issue by nmlgc** [thpatch/thcrap#20]
#### Description

The basic image patching implemented in #12 doesn't have dedicated support for patch stacking. This feature goes a bit further and adds support for overlays and sprite-level replacements to save both redundancy and needless bloat.
#### Prerequisites
- #12 (basic image translation)
#### Implementation

See the [development notes on Touhou Patch Center](http://thpatch.net/wiki/Development_notes/Windows#Images).

**Comment by ROCO-freedom** [comment]
In the patching section about .anm files, all the language patches I have seen, only thcrap and a Chinese translation team's own patching engine can do the patching using only PNG images. So I think, can you take this part out and make it into a library,for other patch engines to use? Be aware that analyzing a file format from scratch can be very difficult. Not to mention writing it as a library. (The main reason is that I am too lazy to analyze the anm file format from scratch...)
The most important reason is that when I use the .anm file packaged by thanm to display in the game, there will be a problem of layering the order of the pictures. Maybe this is just a problem with my packaging.
