### ISSUE TITLE
thcrap does not work with the 1.14 version of touhou 17.5 on Steam

### ISSUE THREAD

**Issue by quest64** [thpatch/thcrap#200]
Today, I tried launching the steam version of touhou 17.5 with a thcrap shortcut with the english translation, but thcrap showed a message saying that the 1.14 version is too old and to use the 1.01 version instead. I'm guessing the 1.14 version (which i think released the on novembre 13 2022) isn't recognized by thcrap right now. I can't go back to an earlier version on steam so, for now, thcrap seems to be incompatible with the steam version.

**Comment by brliron** [comment]
This was a known issue, we needed to work on it.
I just pushed what we worked on. v1.14 isn't fully supported yet, but it's supported well enough to be playable, and to have the story more translated.

**Comment by quest64** [comment]
Oh, cool!
I didn't see it anywhere when I searched, so I posted this just in case.
It now works pretty well on my steam deck.
Thank you very much!
