### ISSUE TITLE
Directory name invalid lutris

### ISSUE THREAD

**Issue by kimikazZZ** [thpatch/thcrap#206]
A few days ago i used to run touhou with thcrap patcher through the lutris and all was fine until i install debian 11. I had the same problem with mint but on lubuntu all was perfect. Is that any other way to run touhou on my native language? Touhou works if i run directly vpatch.exe but without language support.
![image](https://user-images.githubusercontent.com/107315478/215881186-486144da-3630-43e4-ad7e-833945323ee4.png)

**Comment by kimikazZZ** [comment]
damn..... if someone has the same problem just run thcrap.exe as root. Seems like it can't find the right path without permission

**Comment by 32th-System** [comment]
you shouldn't run Wine as root. If permissions are the issue you should fix the permissions for your new user account on your new Linux installation instead

**Comment by Fishaphrodite** [comment]
Where is the game actually located, the prefix too, and does lutris have permissions to both folders? (I believe there is a flatpak for lutris, which will have by default a pretty limited scope as a result, moving the game to a place where it has permissions would for exemple fix this issue).

**Comment by DankRank** [comment]
here are some potentially helpful one-liners

how to find files with wrong ownership:
`find your_directory ! -user your_user_name -exec stat -c '%U %n' -- {} +`
how to fix the ownership:
`find your_directory ! -user your_user_name -exec chown your_user_name: -- {} +`

**Comment by kimikazZZ** [comment]
The point was that thcrap creates .ink file with wrong path. For example as you can see on screenshot the .ink file i've created without root permission for some reason recognizes touhou folder as "C:\" disk when it actually on "Z:\"

**Comment by Fishaphrodite** [comment]
The folder targeted by `C:\users\[name]\Desktop` is typically a symlink to your actual desktop, if your game is located somewhere there, thcrap finding it shouldn't be an issue, and on mint here, I tried making it search for games on the C drive, with one i nthe desktop, and it worked.

I'd say check the wineprefix "desktop" targets the correct folder, that the path exists, or select directly a folder relative to the Z drive if this really is enough to fix it (the Z drive targets `/` and all that is in it).
