### ISSUE TITLE
config.exe for th06 with thcrap can not save the config properly

### ISSUE THREAD

**Issue by xitieshiz2** [thpatch/thcrap#207]
As the title, though config.exe for th06 with thcrap can locate and read`東方紅魔郷.cfg`, it cannot save to the same file, nothing will change with the`Save`button pressed.
The original config.exe for th06 does save, but it both read and write to`搶曽峠杺嫿.cfg`, which cannot be applied when the game starts with`東方紅魔郷.exe`.
_note: this may only happen when the system language environment sets to`Simplified Chinese (China)`, it hasn't been fully tested._

**Comment by 32th-System** [comment]
Fix will come in the next thcrap release https://github.com/thpatch/thcrap/commit/dc1d2a3797a99518091d9c5766f0b5c697c52a5b
