### ISSUE TITLE
migrate to Pycryptodome

### ISSUE THREAD

**Issue by scarf005** [thpatch/thcrap#208]
> This software is no longer maintained.
>
> PyCrypto 2.x is unmaintained, obsolete, and contains security vulnerabilities.

`scripts/release_sign.py`'s dependency, [PyCrypto](https://www.pycrypto.org) is deprecated and it's suggested to use fork of it, [PyCryptodome](https://pypi.org/project/pycryptodome/).

**Comment by 32th-System** [comment]
No modifications are required for the script to work with PyCryptodome the way it does with regular PyCrypto

**Comment by scarf005** [comment]
still, it'd be a good idea to replace PyCrypto with PyCryptodome in README.md. I was preparing a PR for it, would that be okay with you?

**Comment by scarf005** [comment]
oh, it's fixed in 6cb64d3 .
