### ISSUE TITLE
TH 17.5 Don't open

### ISSUE THREAD

**Issue by latot** [thpatch/thcrap#209]
Hi, I have the game on steam, in the past I played it through thcrap and all was working, there has been some time since the last time I played, was close to the release. But today I try to play and the game shows a few seconds with black screen and close it self.  D:

thcrap is updated.

Thx!

**Comment by brliron** [comment]
Hello,
This is a known issue, Tasofro published a new version of the game a few days ago and we need to do some work in order to make thcrap compatible with that new version.
I'm currently in holidays, I'll start working on it when I come back home, next Monday.

**Comment by latot** [comment]
:O Thx! sorry interrupting your holidays, enjoy!

**Comment by brliron** [comment]
Fixed in thpatch/thcrap-tsa@c72a524ecfc476527d0924c5f0e5d4b2c27a57d6

**Comment by latot** [comment]
Yay! Thx :D
