### ISSUE TITLE
Wine + Thcrap unable to launch games (maybe?)

### ISSUE THREAD

**Issue by Fishaphrodite** [thpatch/thcrap#216]
I tried to run Touhou 18 with my usual shortcut to thcrap today on my linux mint desktop, however it seem unable to start, I did notice it was trying to update something the initial time (perhaps it did), then closed the updater without launching the game itself.

I also tried on my steam deck on the side, it couldn't go further than the launcher either it seems, tried with an older proton version as well in case the latest wine and/or proton were at play, this seem to affect all games I tried (though for ease of report, I'm keeping it at 18), an older thcrap install from my linux mint laptop with thcrap_update.dll renamed works (if it isn't, it updates and the same issue happens).

I could grab wine's output (I don't know if it helps or not), as well as the two logs thcrap generated, however I didn't do it for the initial download attempt it did (didn't think about it at the time and did several attempts before realising it wasn't only on my desktop).

[wine output.txt](https://github.com/thpatch/thcrap/files/11415617/wine.output.txt)
[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/11415618/thcrap_log.1.txt)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/11415619/thcrap_log.txt)

I assume I'm not the only one affected (since three of my devices are, one being a steamdeck running steam OS while the others are linux mint based), but I can't speak for others. Also if that's of any relevance, I do not use the steam versions of the games to play.

**Comment by Fishaphrodite** [comment]
(may be related to https://github.com/thpatch/thcrap/issues/215 too, as the user mentions arch, and I had the same issue with EoSD as well, and if aiming for vpatch, it would say dll injection failed as a result of the game not launching)

**Comment by tactikauan** [comment]
Same as #189. It looks like the workaround got reverted before we got a release containing the actual fix.

**Comment by 32th-System** [comment]
yeah I accidentally reverted it xd

**Comment by Raxelgrande** [comment]
Im also affected by this problem, i even tried to run it under 5 different WINE versions, different WINE managers (Bottles and Lutris) and 2 linux distros (Pop!_OS and Arch). 
Here are the backtraces i recollected (from Touhou08 and Touhou15) 
[TH08backtrace.txt](https://github.com/thpatch/thcrap/files/11417903/TH08backtrace.txt)
[TH15backtrace (1).txt](https://github.com/thpatch/thcrap/files/11417905/TH15backtrace.1.txt)

**Comment by brliron** [comment]
I'll make a new build that contains the actual fix this evening (feel free to remind me with a Discord ping if it's still not done by 10 PM CEST)

**Comment by brliron** [comment]
Can you all try with the new thcrap version?

**Comment by Raxelgrande** [comment]
I tested Touhou 8 and 15, they work. This looks fixed

**Comment by Fishaphrodite** [comment]
It works again on the steamdeck as well as mint, thanks a lot!
