### ISSUE TITLE
The incorrect order of th19 music title.

### ISSUE THREAD

**Issue by ROCO-freedom** [thpatch/thcrap#219]
When we were making a Chinese language patch for th19, we found that the music room titles for th19 on thpatch.net were not in the correct order.
![image](https://github.com/thpatch/thcrap/assets/28785008/36119475-0419-446b-ab75-c4ce90d6c9d2)
Current title order.
![image](https://github.com/thpatch/thcrap/assets/28785008/1bd989f0-d3e6-4387-a72c-1fdfe0a12d17)
Correct title order.

Can any people fix it?

**Comment by Dobby233Liu** [comment]
Attempted fix: thpatch/TouhouThemeDB#1

**Comment by Dobby233Liu** [comment]
Also this probably suits [`Touhou Patch Center talk:List of music themes`](https://www.thpatch.net/wiki/Touhou_Patch_Center_talk:List_of_music_themes) better

**Comment by ROCO-freedom** [comment]
@brliron I believe there is no need to modify [https://github.com/thpatch/TouhouThemeDB](url).Perhaps it requires Admin to fix it?

**Comment by DankRank** [comment]
Sorry, that was my fault, should be fixed now.
