### ISSUE TITLE
thcrap_configure_v3: Shortcuts path does not support CJK characters

### ISSUE THREAD

**Issue by xitieshiz2** [thpatch/thcrap#221]
If the game path contains CJK characters, selecting _create shortcuts in the games' folder_ and do the operation of creating shortcuts would make the configure tool crash.
* This issue isn't found in `thcrap_loader` or `thcrap_configure`.

**Comment by brliron** [comment]
Should be fixed by a619a7580a2124d92a399e9069a0ca6d85a6e196, which will be included in the next release
