### ISSUE TITLE
[TH18, TH19] Window opens, then almost immediately closes when running lang_en patch on Wine

### ISSUE THREAD

**Issue by redegg89** [thpatch/thcrap#222]
The games run fine in Steam. I have tried:

- Validating the game files (they were fine)
- earlier games (found this on th19, same thing happens on th18, th17 and lower are fine)
- Looking at the logs (seems like there's files missing, but I don't know where to get them)
- 32-bit wineprefix (same problem)
- Proton (No arguments)
- Standalone patch (Still same errors)
- Different resolutions (borderless dot by dot, windowed 1280x920)

System Info:
Artix Linux kernel 6.3.2-zen1-1-zen
Wine 8.8 staging

Logs (Unmarked are th19):
[thcrap-th18_log.1.txt](https://github.com/thpatch/thcrap/files/11526033/thcrap-th18_log.1.txt)
[thcrap-th18_log.2.txt](https://github.com/thpatch/thcrap/files/11526034/thcrap-th18_log.2.txt)
[thcrap-th18_log.txt](https://github.com/thpatch/thcrap/files/11526035/thcrap-th18_log.txt)

[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/11526042/thcrap_log.1.txt)
[thcrap_log.2.txt](https://github.com/thpatch/thcrap/files/11526043/thcrap_log.2.txt)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/11526044/thcrap_log.txt)

**Comment by redegg89** [comment]
Update: Removed patches individually to try to find what causes it, all of them were removed and TH18 still didn't start with the standalone. Also of note is both are through Steam with Steam on the beta branch

**Comment by brliron** [comment]
Works on my end with both wine 7.7 and wine 8.8.
Can you open the thcrap configuration tool, click on "Configure Settings", select "Enhanced" under Exception Detail, save, try again, and send the logs?

**Comment by redegg89** [comment]
Sadly I can only use the old version of 'thcrap_configure.exe' because I either can't install .NET 4.6.1 on a 64bit prefix or it gives me a black screen with the message `0148:err:d3d:wined3d_context_gl_update_window Failed to get a device context for window 006083B0.` in a 32bit prefix. Is there another way to change the exception detail?

**Comment by brliron** [comment]
Yes, open config/config.js, and set "exception_detail" to 103

**Comment by redegg89** [comment]
Here are the new logs, thanks for the help by the way
[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/11559921/thcrap_log.1.txt)
[thcrap_log.2.txt](https://github.com/thpatch/thcrap/files/11559922/thcrap_log.2.txt)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/11559923/thcrap_log.txt)

**Comment by redegg89** [comment]
I understand this is a relatively small issue, but is there anything I can do while you work on more important issues?

**Comment by redegg89** [comment]
Update:

It works now, for whatever reason. My guess is something with my controller being overridden and connected as a directinput device instead of xinput, but the game still worked fine even without that. Maybe it's from me messing around with VK_ICD_FILENAMES, but it looks like I already tried that.
