### ISSUE TITLE
Files for vx-fixedshots missing

### ISSUE THREAD

**Issue by starlightintheriver** [thpatch/thcrap#240]
Hello, forgive me if this is recorded somewhere and I missed it but I combed the website for anything mentioning it and thought I might as well bring it up.
I tried to install VasteelXolotl's "fixedshots" patch (that fixes the damage bugs for MariB and YoumuC in MoF and WBaWC, respectfully) and found that the files just straight-up didn't get installed on my computer, and only the repo.js did. I was able to fix it by opening up the patch itself on the thpatch mirrors and copying the files over, but it was also a little annoying because the options to download stuff from the mirrors page were quite limited (I could only download one file at a time and had to copy some contents over). It wasn't hard to fix but I figure someone less savvy with computers might not figure it out. 
Again, forgive me if I missed something as this is my first time reporting anything like this.

**Comment by brliron** [comment]
Vasteel just fixed it, can you try again? (note that they renamed themselves to just Vasteel)

**Comment by starlightintheriver** [comment]
Hey, sorry for the late reply.
