### ISSUE TITLE
th155: Spellcards error in th155 1.19beta and 1.21b

### ISSUE THREAD

**Issue by xitieshiz2** [thpatch/thcrap#244]
釣符「可愛い太公望」(Fishing Sign "Adorable Tai Gong Wang")
![ffe85de02007f1397d1cc81e2c8a7041](https://github.com/thpatch/thcrap/assets/75575551/95931a80-b826-428b-9e83-16109489ebc5)
夢符「ご先祖様が見ているぞ」(Dream Sign "Ancestors are Watching you")
![96a55ee4e3cd0e9d8c4068a3026b6bb7](https://github.com/thpatch/thcrap/assets/75575551/e46d3fda-0405-4eb4-99b2-6791cf44ede5)
境界「溢れ出る漂流物」(Boundary "Overflowing Flotsam")
![81b29bfc4beba31c19e99df776659a63](https://github.com/thpatch/thcrap/assets/75575551/f3ed1e73-df07-4a40-824e-a02cf1d5cdd1)
This issue should be caused by a lack of binhacks for versions 1.19beta and 1.21b; the release of spellcard wasn't ended after its declaration.

**Comment by brliron** [comment]
Back when v1.21 and v1.21b got released, I was quite busy, and everything seemed to work by just taking advantage of the v1.19beta4 support, so I didn't pay too much attention to it. Looking at it now, it seems that some things do need to updated for v1.21b (for example, the key in base_tasofro/th155/data/actor/koishi.nut.map is `/Functions/108/Functions/0/Literals/1`, but it should be `/Functions/110/Functions/0/Literals/1`).

I'll work on updating all the nut.map files.

**Comment by brliron** [comment]
fixed in thpatch/thcrap-tsa@0e9b66f1aba3aaabba5adc8f3e0dc47481bcebb7
