### ISSUE TITLE
Th06 EoSD: the title screen is messed up (likely a regression)

### ISSUE THREAD

**Issue by kikones34** [thpatch/thcrap#247]
In Touhou 6, the English game title is disfigured as follows:

![2023-11-22-000745_東方紅魔郷](https://github.com/thpatch/thcrap/assets/4391024/45dfedf4-509b-45d0-a307-d8eab54b6184)

This appears to be caused by the file `title03.anm.jdiff`, which was last updated on 2023-Oct-22 21:13 with the following contents:

```js
{
	"sprites": {
		"1": [0, 185, 256, 36],
		"2": [0, 220, 256, 40]
	}
}
```

I removed the contents of this file and the title seems to get fixed:

![image](https://github.com/thpatch/thcrap/assets/4391024/a28adfec-e4b7-4cfa-bafa-db3c610c7f0b)

**Comment by brliron** [comment]
I removed it on the server side. Thanks for finding out where that problem comes from!
