### ISSUE TITLE
TH7 PCB: Translation Patch Error

### ISSUE THREAD

**Issue by Emneisium** [thpatch/thcrap#249]
Since the latest THCrap update, there has been an issue with PCB where I get an error thrown at me when booting the game.
![image](https://github.com/thpatch/thcrap/assets/67762921/a2ce1112-cb64-4b06-b1c7-54d7ad883909)
Upon cancelling, the game will boot but in it's original language.
This only effects the translation patches, everything else works fine. I've tested this on the other patched games I have at the moment (6 and 10) and I have not gotten the same type of error.

**Comment by brliron** [comment]
Fixed in thpatch/thcrap-tsa@7fad0ac7e10bcc0847206b5257498429e4dcf2b6, sorry for the inconvenience (I made a typo while working on making the game's error messages translatable).

**Comment by Emneisium** [comment]
Thanks man it works
