### ISSUE TITLE
VPatch error when running from a thcrap shortcut

### ISSUE THREAD

**Issue by LambdaLaboratories** [thpatch/thcrap#257]
Example:
![imagen](https://github.com/thpatch/thcrap/assets/114331875/b5961be9-672e-47c8-8bd6-42d35222f0aa)
It worked perfectly before but, maybe it's because I messed around with some of the files on my computer, but this error is being thrown now

- The game executables are named correctly, even EoSD
- Double clicking on "vpatch.exe" itself on every game works perfectly fine
- This is after performing a clean install of everything, except for th6-8 which I dont have on steam
- The installations that don't use vpatch launch correctly
- To reiterate, everything was working fine until I moved thcrap into another folder. I reinstalled the entire patcher to make sure there weren't any issues with the shortcuts. 

This is an odd issue, I'm probably missing a library or something that would allow thcrap to function normally but I can't be sure, everything should work fine otherwise

Hope to see this issue be fixed soon 

Lambdatories

**Comment by brliron** [comment]
Known issue with the latest version released 2 hours ago, we're working on it

**Comment by brliron** [comment]
Rolled back to the previous version while we're working on a fix

**Comment by LambdaLaboratories** [comment]
alright 👍

**Comment by brliron** [comment]
Fixed with the version [2024-06-07](https://github.com/thpatch/thcrap/releases/tag/2024-06-07).
Please reopen this issue if this new version reintroduces this error.
