### ISSUE TITLE
[th175] Translating a image could crash the game

### ISSUE THREAD

**Issue by yzdnn** [thpatch/thcrap#269]
th175/data/sprite/player_murasa/water_use_font.gif ←this one
When the translated image is displayed in the game, the game would freeze and then crash, 
making Murasa's tutorial stage impossible to complete.
<img width="320" alt="ss" src="https://github.com/user-attachments/assets/b9d109ba-a1a3-43bf-ae8f-aa1e4e946434">
↑Where the crash happens

**Comment by Dobby233Liu** [comment]
For both lang_en and lang_zh-hans you uploaded PNGs for th175-data-sprite-player_murasa-water_use_font.gif, what if you uploaded actual GIFs instead? I see lang_hu did that and I don't remember their crew mentioning a crash. You can create GIFs with something like [ezgif](https://ezgif.com/maker)

**Comment by yzdnn** [comment]
wow it worked! thank you!
I'll update those images now

**Comment by yzdnn** [comment]
Fixed.
Solution: Use actual GIFs instead.

**Comment by yzdnn** [comment]
Fixed.
Solution: Use actual GIFs instead.
