### ISSUE TITLE
Playism version of Double Dealing Character crashes immediately

### ISSUE THREAD

**Issue by minneyar** [thpatch/thcrap#51]
For reference, I'm running 64-bit Windows 8.1.  I have DDC installed at D:\Touhou\Touhou 14 - Double Dealing Character\, and thcrap is at D:\Touhou\thcrap\ .

I bought and downloaded the full version of DDC from Playism, and I downloaded the latest version of thcrap from thpatch.net and ran it.  I selected the English language patch and pointed it to the right directory, and it generated shortcuts that seem correct.  I can run the shortcut to custom.exe without any problems, but when I try to run th14, it crashes immediately.  I can run th14 by itself without any problems.

**Comment by nmlgc** [comment]
As of thpatch/thcrap-tsa@96570a1be623b4248d4de72cd1bb121e4bf8de4d, this should now have been fixed. Most of the translation support should now have been adapted for the Playism build, with spell card alignment being the most notable thing still missing. Please use the issue at thpatch/thcrap-tsa#4 if any other further problems remain.
