### ISSUE TITLE
TH10 Mountain of Faith loading screen corruption

### ISSUE THREAD

**Issue by Timecrash** [thpatch/thcrap#55]
Updated thcrap to the [2016-08-10 build](https://github.com/thpatch/thcrap/releases/tag/2016-08-10), and I'm finding that the loading screen for Mountain of Faith isn't displaying properly. I run Mountain of Faith with vpatch, but I tested it on both that exe and the main th10.exe. This is running at 1280x960 windowed, thanks to vpatch, but it still applies if I run it on the main exe with 640x480.

No other game that I tried had this problem. The game itself works fine, though, it's just the loading screen that seems buggy.

Log file attached: [thcrap_log.txt](https://github.com/thpatch/thcrap/files/452116/thcrap_log.txt)

![TH10 Bug.png](https://bitbucket.org/repo/R5RjAo/images/2964159425-TH10%20Bug.png)

**Comment by nmlgc** [comment]
This was a compatibility issue when running on top of gensokyo.org's static English patch rather than the original Japanese version, and is fixed as of the [2018-10-22 build](https://github.com/thpatch/thcrap/releases/tag/2018-10-22).
