### ISSUE TITLE
Replace cutted character sprites with non-cutted ones (mod suggestion) (enhancement)

### ISSUE THREAD

**Issue by Zrrg** [thpatch/thcrap#61]
As you know, some games, starting from EoSD to IN (if i remember correctly) are using cutted character sprites in-game, probably due to technical restrictions.  If it was possible to replace with original non-cut sprites (if they are presented in game resources), or with manually restored ones [like this one](http://images5.fanpop.com/image/photos/27900000/ZUN-Flandre-Reference-flandre-scarlet-27971155-433-497.jpg) this would be a huge enhancement. Also overlay sprites over the interface like in DDC or LoLK is interesting too.

**Comment by 32th-System** [comment]
The game already displays portraits exactly as they appear in the game data; which means that portraits in the game data are also cut off. The image you posted is fanart. If there is demand for something like this, a separate patch should do this
