### ISSUE TITLE
EOSD crashes if title00.jpg is replaced

### ISSUE THREAD

**Issue by opm0** [thpatch/thcrap#62]
All spanish language patches crash on start unless you go offline and delete title00.jpg from "es" (and es-ve if you're using that one)

**Comment by Zrrg** [comment]
It must be not bigger than original in byte size, approx 100KB, and jpeg. We had same issue here.
:point_up: [October 2, 2016 4:49 PM](https://gitter.im/thpatch/thcrap?at=57f1105eb0ff456d3adab594)

**Comment by nmlgc** [comment]
Fixed as of https://github.com/thpatch/thcrap-tsa/commit/252c1ffac8b427c8e0696a152c1b0ca2e5dc0ea5. Now, you can even use PNGs in place of JPEG files, in all 5 games that have them. (These still have to have a `.jpg` extension.)
