### ISSUE TITLE
[AoCF] Missing translations in config screen

### ISSUE THREAD

**Issue by brliron** [thpatch/thcrap#73]
On the attached image, some kanjis need to be translatable.
![](https://cdn.discordapp.com/attachments/253898950099075085/435550807891640320/2018-04-16_23_24_58-Touhou_Hyouibana__Antinomy_of_Common_FlowersVer1.04.png)

**Comment by IgoSplashman** [comment]
These are Japanese counter words and can be simply replaced with numbers in most languages.
https://en.wikipedia.org/wiki/Japanese_counter_word

They're already listed and supported in data/system/practice/item.csv.jdiff
https://www.thpatch.net/wiki/Th155/Nut_and_Csv_strings/en

For some reason, **ONLY the 0 counters show the Kanji**, the rest of the numbers are fine.

**Comment by brliron** [comment]
Fixed in  thpatch/TouhouPatchCenter@93d1e5f9d21b76e3207e84d4cb277af58dbcee9c
