### ISSUE TITLE
thcrap_configure: Link `thcrap_update` dynamically

### ISSUE THREAD

**Issue by nmlgc** [thpatch/thcrap#9]
#### Description

We want users to opt out of any automatic updating functionality of both the patches and thcrap itself by simply deleting `thcrap_update.dll`. This is no problem as far as the base engine is concerned, but the configuration tool has a static link to this DLL.
#### Prerequisites

None.

**Comment by brliron** [comment]
Done in 103f3433594cb48ef099d28be6c8c223230a49fc
